// Generated by gencpp from file minik_ros_wrapper/minikGetLineFollowerSensorMsg.msg
// DO NOT EDIT!


#ifndef MINIK_ROS_WRAPPER_MESSAGE_MINIKGETLINEFOLLOWERSENSORMSG_H
#define MINIK_ROS_WRAPPER_MESSAGE_MINIKGETLINEFOLLOWERSENSORMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace minik_ros_wrapper
{
template <class ContainerAllocator>
struct minikGetLineFollowerSensorMsg_
{
  typedef minikGetLineFollowerSensorMsg_<ContainerAllocator> Type;

  minikGetLineFollowerSensorMsg_()
    : rightSensor(0)
    , middleSensor(0)
    , leftSensor(0)  {
    }
  minikGetLineFollowerSensorMsg_(const ContainerAllocator& _alloc)
    : rightSensor(0)
    , middleSensor(0)
    , leftSensor(0)  {
  (void)_alloc;
    }



   typedef uint8_t _rightSensor_type;
  _rightSensor_type rightSensor;

   typedef uint8_t _middleSensor_type;
  _middleSensor_type middleSensor;

   typedef uint8_t _leftSensor_type;
  _leftSensor_type leftSensor;





  typedef boost::shared_ptr< ::minik_ros_wrapper::minikGetLineFollowerSensorMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::minik_ros_wrapper::minikGetLineFollowerSensorMsg_<ContainerAllocator> const> ConstPtr;

}; // struct minikGetLineFollowerSensorMsg_

typedef ::minik_ros_wrapper::minikGetLineFollowerSensorMsg_<std::allocator<void> > minikGetLineFollowerSensorMsg;

typedef boost::shared_ptr< ::minik_ros_wrapper::minikGetLineFollowerSensorMsg > minikGetLineFollowerSensorMsgPtr;
typedef boost::shared_ptr< ::minik_ros_wrapper::minikGetLineFollowerSensorMsg const> minikGetLineFollowerSensorMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::minik_ros_wrapper::minikGetLineFollowerSensorMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::minik_ros_wrapper::minikGetLineFollowerSensorMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace minik_ros_wrapper

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'minik_ros_wrapper': ['/home/berkay/catkin_ws/src/minik_realization/minik_packages/minik_ros_wrapper/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::minik_ros_wrapper::minikGetLineFollowerSensorMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::minik_ros_wrapper::minikGetLineFollowerSensorMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::minik_ros_wrapper::minikGetLineFollowerSensorMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::minik_ros_wrapper::minikGetLineFollowerSensorMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::minik_ros_wrapper::minikGetLineFollowerSensorMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::minik_ros_wrapper::minikGetLineFollowerSensorMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::minik_ros_wrapper::minikGetLineFollowerSensorMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "117f4dd679610c07fd2b537377a09014";
  }

  static const char* value(const ::minik_ros_wrapper::minikGetLineFollowerSensorMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x117f4dd679610c07ULL;
  static const uint64_t static_value2 = 0xfd2b537377a09014ULL;
};

template<class ContainerAllocator>
struct DataType< ::minik_ros_wrapper::minikGetLineFollowerSensorMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "minik_ros_wrapper/minikGetLineFollowerSensorMsg";
  }

  static const char* value(const ::minik_ros_wrapper::minikGetLineFollowerSensorMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::minik_ros_wrapper::minikGetLineFollowerSensorMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Minik Get Line Follower Message\n\
\n\
char rightSensor\n\
char middleSensor\n\
char leftSensor\n\
";
  }

  static const char* value(const ::minik_ros_wrapper::minikGetLineFollowerSensorMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::minik_ros_wrapper::minikGetLineFollowerSensorMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rightSensor);
      stream.next(m.middleSensor);
      stream.next(m.leftSensor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct minikGetLineFollowerSensorMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::minik_ros_wrapper::minikGetLineFollowerSensorMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::minik_ros_wrapper::minikGetLineFollowerSensorMsg_<ContainerAllocator>& v)
  {
    s << indent << "rightSensor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rightSensor);
    s << indent << "middleSensor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.middleSensor);
    s << indent << "leftSensor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.leftSensor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MINIK_ROS_WRAPPER_MESSAGE_MINIKGETLINEFOLLOWERSENSORMSG_H
