// Generated by gencpp from file minik_ros_wrapper/minikSetConfigMsg.msg
// DO NOT EDIT!


#ifndef MINIK_ROS_WRAPPER_MESSAGE_MINIKSETCONFIGMSG_H
#define MINIK_ROS_WRAPPER_MESSAGE_MINIKSETCONFIGMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace minik_ros_wrapper
{
template <class ContainerAllocator>
struct minikSetConfigMsg_
{
  typedef minikSetConfigMsg_<ContainerAllocator> Type;

  minikSetConfigMsg_()
    : isSpeedSendON(false)
    , isPositionSendON(false)
    , frequency(0)  {
    }
  minikSetConfigMsg_(const ContainerAllocator& _alloc)
    : isSpeedSendON(false)
    , isPositionSendON(false)
    , frequency(0)  {
  (void)_alloc;
    }



   typedef uint8_t _isSpeedSendON_type;
  _isSpeedSendON_type isSpeedSendON;

   typedef uint8_t _isPositionSendON_type;
  _isPositionSendON_type isPositionSendON;

   typedef uint8_t _frequency_type;
  _frequency_type frequency;





  typedef boost::shared_ptr< ::minik_ros_wrapper::minikSetConfigMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::minik_ros_wrapper::minikSetConfigMsg_<ContainerAllocator> const> ConstPtr;

}; // struct minikSetConfigMsg_

typedef ::minik_ros_wrapper::minikSetConfigMsg_<std::allocator<void> > minikSetConfigMsg;

typedef boost::shared_ptr< ::minik_ros_wrapper::minikSetConfigMsg > minikSetConfigMsgPtr;
typedef boost::shared_ptr< ::minik_ros_wrapper::minikSetConfigMsg const> minikSetConfigMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::minik_ros_wrapper::minikSetConfigMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::minik_ros_wrapper::minikSetConfigMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace minik_ros_wrapper

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'minik_ros_wrapper': ['/home/berkay/catkin_ws/src/minik_realization/minik_packages/minik_ros_wrapper/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::minik_ros_wrapper::minikSetConfigMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::minik_ros_wrapper::minikSetConfigMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::minik_ros_wrapper::minikSetConfigMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::minik_ros_wrapper::minikSetConfigMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::minik_ros_wrapper::minikSetConfigMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::minik_ros_wrapper::minikSetConfigMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::minik_ros_wrapper::minikSetConfigMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e4dff864fd41bf1461aaa087ae928002";
  }

  static const char* value(const ::minik_ros_wrapper::minikSetConfigMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe4dff864fd41bf14ULL;
  static const uint64_t static_value2 = 0x61aaa087ae928002ULL;
};

template<class ContainerAllocator>
struct DataType< ::minik_ros_wrapper::minikSetConfigMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "minik_ros_wrapper/minikSetConfigMsg";
  }

  static const char* value(const ::minik_ros_wrapper::minikSetConfigMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::minik_ros_wrapper::minikSetConfigMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Minik Set Config Command\n\
\n\
bool isSpeedSendON\n\
bool isPositionSendON\n\
char frequency\n\
";
  }

  static const char* value(const ::minik_ros_wrapper::minikSetConfigMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::minik_ros_wrapper::minikSetConfigMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isSpeedSendON);
      stream.next(m.isPositionSendON);
      stream.next(m.frequency);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct minikSetConfigMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::minik_ros_wrapper::minikSetConfigMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::minik_ros_wrapper::minikSetConfigMsg_<ContainerAllocator>& v)
  {
    s << indent << "isSpeedSendON: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isSpeedSendON);
    s << indent << "isPositionSendON: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isPositionSendON);
    s << indent << "frequency: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.frequency);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MINIK_ROS_WRAPPER_MESSAGE_MINIKSETCONFIGMSG_H
