// Generated by gencpp from file minik_ros_wrapper/minikGetDistSensorMsg.msg
// DO NOT EDIT!


#ifndef MINIK_ROS_WRAPPER_MESSAGE_MINIKGETDISTSENSORMSG_H
#define MINIK_ROS_WRAPPER_MESSAGE_MINIKGETDISTSENSORMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace minik_ros_wrapper
{
template <class ContainerAllocator>
struct minikGetDistSensorMsg_
{
  typedef minikGetDistSensorMsg_<ContainerAllocator> Type;

  minikGetDistSensorMsg_()
    : rightSensor(0)
    , leftSensor(0)  {
    }
  minikGetDistSensorMsg_(const ContainerAllocator& _alloc)
    : rightSensor(0)
    , leftSensor(0)  {
  (void)_alloc;
    }



   typedef int16_t _rightSensor_type;
  _rightSensor_type rightSensor;

   typedef int16_t _leftSensor_type;
  _leftSensor_type leftSensor;





  typedef boost::shared_ptr< ::minik_ros_wrapper::minikGetDistSensorMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::minik_ros_wrapper::minikGetDistSensorMsg_<ContainerAllocator> const> ConstPtr;

}; // struct minikGetDistSensorMsg_

typedef ::minik_ros_wrapper::minikGetDistSensorMsg_<std::allocator<void> > minikGetDistSensorMsg;

typedef boost::shared_ptr< ::minik_ros_wrapper::minikGetDistSensorMsg > minikGetDistSensorMsgPtr;
typedef boost::shared_ptr< ::minik_ros_wrapper::minikGetDistSensorMsg const> minikGetDistSensorMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::minik_ros_wrapper::minikGetDistSensorMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::minik_ros_wrapper::minikGetDistSensorMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace minik_ros_wrapper

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'minik_ros_wrapper': ['/home/berkay/catkin_ws/src/minik_realization/minik_packages/minik_ros_wrapper/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::minik_ros_wrapper::minikGetDistSensorMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::minik_ros_wrapper::minikGetDistSensorMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::minik_ros_wrapper::minikGetDistSensorMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::minik_ros_wrapper::minikGetDistSensorMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::minik_ros_wrapper::minikGetDistSensorMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::minik_ros_wrapper::minikGetDistSensorMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::minik_ros_wrapper::minikGetDistSensorMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ecaa6ae02155044a20eae821d6e0498f";
  }

  static const char* value(const ::minik_ros_wrapper::minikGetDistSensorMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xecaa6ae02155044aULL;
  static const uint64_t static_value2 = 0x20eae821d6e0498fULL;
};

template<class ContainerAllocator>
struct DataType< ::minik_ros_wrapper::minikGetDistSensorMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "minik_ros_wrapper/minikGetDistSensorMsg";
  }

  static const char* value(const ::minik_ros_wrapper::minikGetDistSensorMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::minik_ros_wrapper::minikGetDistSensorMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Minik Get Sharp Distance Sensor Message\n\
\n\
int16 rightSensor\n\
int16 leftSensor\n\
";
  }

  static const char* value(const ::minik_ros_wrapper::minikGetDistSensorMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::minik_ros_wrapper::minikGetDistSensorMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rightSensor);
      stream.next(m.leftSensor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct minikGetDistSensorMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::minik_ros_wrapper::minikGetDistSensorMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::minik_ros_wrapper::minikGetDistSensorMsg_<ContainerAllocator>& v)
  {
    s << indent << "rightSensor: ";
    Printer<int16_t>::stream(s, indent + "  ", v.rightSensor);
    s << indent << "leftSensor: ";
    Printer<int16_t>::stream(s, indent + "  ", v.leftSensor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MINIK_ROS_WRAPPER_MESSAGE_MINIKGETDISTSENSORMSG_H
