// Generated by gencpp from file minik_ros_wrapper/minikGetButtonMsg.msg
// DO NOT EDIT!


#ifndef MINIK_ROS_WRAPPER_MESSAGE_MINIKGETBUTTONMSG_H
#define MINIK_ROS_WRAPPER_MESSAGE_MINIKGETBUTTONMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace minik_ros_wrapper
{
template <class ContainerAllocator>
struct minikGetButtonMsg_
{
  typedef minikGetButtonMsg_<ContainerAllocator> Type;

  minikGetButtonMsg_()
    : isButton1Pressed(false)
    , isButton2Pressed(false)
    , isButton3Pressed(false)  {
    }
  minikGetButtonMsg_(const ContainerAllocator& _alloc)
    : isButton1Pressed(false)
    , isButton2Pressed(false)
    , isButton3Pressed(false)  {
  (void)_alloc;
    }



   typedef uint8_t _isButton1Pressed_type;
  _isButton1Pressed_type isButton1Pressed;

   typedef uint8_t _isButton2Pressed_type;
  _isButton2Pressed_type isButton2Pressed;

   typedef uint8_t _isButton3Pressed_type;
  _isButton3Pressed_type isButton3Pressed;





  typedef boost::shared_ptr< ::minik_ros_wrapper::minikGetButtonMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::minik_ros_wrapper::minikGetButtonMsg_<ContainerAllocator> const> ConstPtr;

}; // struct minikGetButtonMsg_

typedef ::minik_ros_wrapper::minikGetButtonMsg_<std::allocator<void> > minikGetButtonMsg;

typedef boost::shared_ptr< ::minik_ros_wrapper::minikGetButtonMsg > minikGetButtonMsgPtr;
typedef boost::shared_ptr< ::minik_ros_wrapper::minikGetButtonMsg const> minikGetButtonMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::minik_ros_wrapper::minikGetButtonMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::minik_ros_wrapper::minikGetButtonMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace minik_ros_wrapper

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'minik_ros_wrapper': ['/home/berkay/catkin_ws/src/minik_realization/minik_packages/minik_ros_wrapper/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::minik_ros_wrapper::minikGetButtonMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::minik_ros_wrapper::minikGetButtonMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::minik_ros_wrapper::minikGetButtonMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::minik_ros_wrapper::minikGetButtonMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::minik_ros_wrapper::minikGetButtonMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::minik_ros_wrapper::minikGetButtonMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::minik_ros_wrapper::minikGetButtonMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3853358d8e2e329f368156066a21f0b2";
  }

  static const char* value(const ::minik_ros_wrapper::minikGetButtonMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3853358d8e2e329fULL;
  static const uint64_t static_value2 = 0x368156066a21f0b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::minik_ros_wrapper::minikGetButtonMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "minik_ros_wrapper/minikGetButtonMsg";
  }

  static const char* value(const ::minik_ros_wrapper::minikGetButtonMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::minik_ros_wrapper::minikGetButtonMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Minik Get Button Message\n\
\n\
bool isButton1Pressed\n\
bool isButton2Pressed\n\
bool isButton3Pressed\n\
";
  }

  static const char* value(const ::minik_ros_wrapper::minikGetButtonMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::minik_ros_wrapper::minikGetButtonMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isButton1Pressed);
      stream.next(m.isButton2Pressed);
      stream.next(m.isButton3Pressed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct minikGetButtonMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::minik_ros_wrapper::minikGetButtonMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::minik_ros_wrapper::minikGetButtonMsg_<ContainerAllocator>& v)
  {
    s << indent << "isButton1Pressed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isButton1Pressed);
    s << indent << "isButton2Pressed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isButton2Pressed);
    s << indent << "isButton3Pressed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isButton3Pressed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MINIK_ROS_WRAPPER_MESSAGE_MINIKGETBUTTONMSG_H
