// Generated by gencpp from file minik_ros_wrapper/minikSetVelocityMsg.msg
// DO NOT EDIT!


#ifndef MINIK_ROS_WRAPPER_MESSAGE_MINIKSETVELOCITYMSG_H
#define MINIK_ROS_WRAPPER_MESSAGE_MINIKSETVELOCITYMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace minik_ros_wrapper
{
template <class ContainerAllocator>
struct minikSetVelocityMsg_
{
  typedef minikSetVelocityMsg_<ContainerAllocator> Type;

  minikSetVelocityMsg_()
    : motorID()
    , velocity()  {
    }
  minikSetVelocityMsg_(const ContainerAllocator& _alloc)
    : motorID(_alloc)
    , velocity(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _motorID_type;
  _motorID_type motorID;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::minik_ros_wrapper::minikSetVelocityMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::minik_ros_wrapper::minikSetVelocityMsg_<ContainerAllocator> const> ConstPtr;

}; // struct minikSetVelocityMsg_

typedef ::minik_ros_wrapper::minikSetVelocityMsg_<std::allocator<void> > minikSetVelocityMsg;

typedef boost::shared_ptr< ::minik_ros_wrapper::minikSetVelocityMsg > minikSetVelocityMsgPtr;
typedef boost::shared_ptr< ::minik_ros_wrapper::minikSetVelocityMsg const> minikSetVelocityMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::minik_ros_wrapper::minikSetVelocityMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::minik_ros_wrapper::minikSetVelocityMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace minik_ros_wrapper

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'minik_ros_wrapper': ['/home/berkay/catkin_ws/src/minik_realization/minik_packages/minik_ros_wrapper/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::minik_ros_wrapper::minikSetVelocityMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::minik_ros_wrapper::minikSetVelocityMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::minik_ros_wrapper::minikSetVelocityMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::minik_ros_wrapper::minikSetVelocityMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::minik_ros_wrapper::minikSetVelocityMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::minik_ros_wrapper::minikSetVelocityMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::minik_ros_wrapper::minikSetVelocityMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c8adc9ee4fc03605a59580c725817899";
  }

  static const char* value(const ::minik_ros_wrapper::minikSetVelocityMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc8adc9ee4fc03605ULL;
  static const uint64_t static_value2 = 0xa59580c725817899ULL;
};

template<class ContainerAllocator>
struct DataType< ::minik_ros_wrapper::minikSetVelocityMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "minik_ros_wrapper/minikSetVelocityMsg";
  }

  static const char* value(const ::minik_ros_wrapper::minikSetVelocityMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::minik_ros_wrapper::minikSetVelocityMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Minik Set Velocity Command\n\
\n\
int32[] motorID\n\
int32[] velocity\n\
";
  }

  static const char* value(const ::minik_ros_wrapper::minikSetVelocityMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::minik_ros_wrapper::minikSetVelocityMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motorID);
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct minikSetVelocityMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::minik_ros_wrapper::minikSetVelocityMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::minik_ros_wrapper::minikSetVelocityMsg_<ContainerAllocator>& v)
  {
    s << indent << "motorID[]" << std::endl;
    for (size_t i = 0; i < v.motorID.size(); ++i)
    {
      s << indent << "  motorID[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.motorID[i]);
    }
    s << indent << "velocity[]" << std::endl;
    for (size_t i = 0; i < v.velocity.size(); ++i)
    {
      s << indent << "  velocity[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.velocity[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MINIK_ROS_WRAPPER_MESSAGE_MINIKSETVELOCITYMSG_H
