// Generated by gencpp from file minik_ros_wrapper/minikGetPositionMsg.msg
// DO NOT EDIT!


#ifndef MINIK_ROS_WRAPPER_MESSAGE_MINIKGETPOSITIONMSG_H
#define MINIK_ROS_WRAPPER_MESSAGE_MINIKGETPOSITIONMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace minik_ros_wrapper
{
template <class ContainerAllocator>
struct minikGetPositionMsg_
{
  typedef minikGetPositionMsg_<ContainerAllocator> Type;

  minikGetPositionMsg_()
    : motorID(0)
    , position(0)  {
    }
  minikGetPositionMsg_(const ContainerAllocator& _alloc)
    : motorID(0)
    , position(0)  {
  (void)_alloc;
    }



   typedef int32_t _motorID_type;
  _motorID_type motorID;

   typedef int32_t _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::minik_ros_wrapper::minikGetPositionMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::minik_ros_wrapper::minikGetPositionMsg_<ContainerAllocator> const> ConstPtr;

}; // struct minikGetPositionMsg_

typedef ::minik_ros_wrapper::minikGetPositionMsg_<std::allocator<void> > minikGetPositionMsg;

typedef boost::shared_ptr< ::minik_ros_wrapper::minikGetPositionMsg > minikGetPositionMsgPtr;
typedef boost::shared_ptr< ::minik_ros_wrapper::minikGetPositionMsg const> minikGetPositionMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::minik_ros_wrapper::minikGetPositionMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::minik_ros_wrapper::minikGetPositionMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace minik_ros_wrapper

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'minik_ros_wrapper': ['/home/berkay/catkin_ws/src/minik_realization/minik_packages/minik_ros_wrapper/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::minik_ros_wrapper::minikGetPositionMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::minik_ros_wrapper::minikGetPositionMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::minik_ros_wrapper::minikGetPositionMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::minik_ros_wrapper::minikGetPositionMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::minik_ros_wrapper::minikGetPositionMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::minik_ros_wrapper::minikGetPositionMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::minik_ros_wrapper::minikGetPositionMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9484186d0d818e0301bf0d58107b9a65";
  }

  static const char* value(const ::minik_ros_wrapper::minikGetPositionMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9484186d0d818e03ULL;
  static const uint64_t static_value2 = 0x01bf0d58107b9a65ULL;
};

template<class ContainerAllocator>
struct DataType< ::minik_ros_wrapper::minikGetPositionMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "minik_ros_wrapper/minikGetPositionMsg";
  }

  static const char* value(const ::minik_ros_wrapper::minikGetPositionMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::minik_ros_wrapper::minikGetPositionMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Minik Get Position Message\n\
\n\
int32 motorID\n\
int32 position\n\
";
  }

  static const char* value(const ::minik_ros_wrapper::minikGetPositionMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::minik_ros_wrapper::minikGetPositionMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motorID);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct minikGetPositionMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::minik_ros_wrapper::minikGetPositionMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::minik_ros_wrapper::minikGetPositionMsg_<ContainerAllocator>& v)
  {
    s << indent << "motorID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.motorID);
    s << indent << "position: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MINIK_ROS_WRAPPER_MESSAGE_MINIKGETPOSITIONMSG_H
