// Generated by gencpp from file minik_ros_wrapper/minikSetLedMsg.msg
// DO NOT EDIT!


#ifndef MINIK_ROS_WRAPPER_MESSAGE_MINIKSETLEDMSG_H
#define MINIK_ROS_WRAPPER_MESSAGE_MINIKSETLEDMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace minik_ros_wrapper
{
template <class ContainerAllocator>
struct minikSetLedMsg_
{
  typedef minikSetLedMsg_<ContainerAllocator> Type;

  minikSetLedMsg_()
    : isLed1ON(false)
    , isLed2ON(false)  {
    }
  minikSetLedMsg_(const ContainerAllocator& _alloc)
    : isLed1ON(false)
    , isLed2ON(false)  {
  (void)_alloc;
    }



   typedef uint8_t _isLed1ON_type;
  _isLed1ON_type isLed1ON;

   typedef uint8_t _isLed2ON_type;
  _isLed2ON_type isLed2ON;





  typedef boost::shared_ptr< ::minik_ros_wrapper::minikSetLedMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::minik_ros_wrapper::minikSetLedMsg_<ContainerAllocator> const> ConstPtr;

}; // struct minikSetLedMsg_

typedef ::minik_ros_wrapper::minikSetLedMsg_<std::allocator<void> > minikSetLedMsg;

typedef boost::shared_ptr< ::minik_ros_wrapper::minikSetLedMsg > minikSetLedMsgPtr;
typedef boost::shared_ptr< ::minik_ros_wrapper::minikSetLedMsg const> minikSetLedMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::minik_ros_wrapper::minikSetLedMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::minik_ros_wrapper::minikSetLedMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace minik_ros_wrapper

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'minik_ros_wrapper': ['/home/berkay/catkin_ws/src/minik_realization/minik_packages/minik_ros_wrapper/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::minik_ros_wrapper::minikSetLedMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::minik_ros_wrapper::minikSetLedMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::minik_ros_wrapper::minikSetLedMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::minik_ros_wrapper::minikSetLedMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::minik_ros_wrapper::minikSetLedMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::minik_ros_wrapper::minikSetLedMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::minik_ros_wrapper::minikSetLedMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "416c0731914825378ec0a0ce9d25cbb7";
  }

  static const char* value(const ::minik_ros_wrapper::minikSetLedMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x416c073191482537ULL;
  static const uint64_t static_value2 = 0x8ec0a0ce9d25cbb7ULL;
};

template<class ContainerAllocator>
struct DataType< ::minik_ros_wrapper::minikSetLedMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "minik_ros_wrapper/minikSetLedMsg";
  }

  static const char* value(const ::minik_ros_wrapper::minikSetLedMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::minik_ros_wrapper::minikSetLedMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Minik Set Led Command\n\
\n\
bool isLed1ON\n\
bool isLed2ON\n\
";
  }

  static const char* value(const ::minik_ros_wrapper::minikSetLedMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::minik_ros_wrapper::minikSetLedMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isLed1ON);
      stream.next(m.isLed2ON);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct minikSetLedMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::minik_ros_wrapper::minikSetLedMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::minik_ros_wrapper::minikSetLedMsg_<ContainerAllocator>& v)
  {
    s << indent << "isLed1ON: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isLed1ON);
    s << indent << "isLed2ON: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isLed2ON);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MINIK_ROS_WRAPPER_MESSAGE_MINIKSETLEDMSG_H
