# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from minik_ros_wrapper/minikGetLedMsg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class minikGetLedMsg(genpy.Message):
  _md5sum = "416c0731914825378ec0a0ce9d25cbb7"
  _type = "minik_ros_wrapper/minikGetLedMsg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# Minik Get Led Message

bool isLed1ON
bool isLed2ON
"""
  __slots__ = ['isLed1ON','isLed2ON']
  _slot_types = ['bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       isLed1ON,isLed2ON

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(minikGetLedMsg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.isLed1ON is None:
        self.isLed1ON = False
      if self.isLed2ON is None:
        self.isLed2ON = False
    else:
      self.isLed1ON = False
      self.isLed2ON = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2B().pack(_x.isLed1ON, _x.isLed2ON))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.isLed1ON, _x.isLed2ON,) = _get_struct_2B().unpack(str[start:end])
      self.isLed1ON = bool(self.isLed1ON)
      self.isLed2ON = bool(self.isLed2ON)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2B().pack(_x.isLed1ON, _x.isLed2ON))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.isLed1ON, _x.isLed2ON,) = _get_struct_2B().unpack(str[start:end])
      self.isLed1ON = bool(self.isLed1ON)
      self.isLed2ON = bool(self.isLed2ON)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B = None
def _get_struct_2B():
    global _struct_2B
    if _struct_2B is None:
        _struct_2B = struct.Struct("<2B")
    return _struct_2B
