# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from minik_ros_wrapper/minikSetConfigMsg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class minikSetConfigMsg(genpy.Message):
  _md5sum = "e4dff864fd41bf1461aaa087ae928002"
  _type = "minik_ros_wrapper/minikSetConfigMsg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# Minik Set Config Command

bool isSpeedSendON
bool isPositionSendON
char frequency
"""
  __slots__ = ['isSpeedSendON','isPositionSendON','frequency']
  _slot_types = ['bool','bool','char']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       isSpeedSendON,isPositionSendON,frequency

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(minikSetConfigMsg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.isSpeedSendON is None:
        self.isSpeedSendON = False
      if self.isPositionSendON is None:
        self.isPositionSendON = False
      if self.frequency is None:
        self.frequency = 0
    else:
      self.isSpeedSendON = False
      self.isPositionSendON = False
      self.frequency = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3B().pack(_x.isSpeedSendON, _x.isPositionSendON, _x.frequency))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.isSpeedSendON, _x.isPositionSendON, _x.frequency,) = _get_struct_3B().unpack(str[start:end])
      self.isSpeedSendON = bool(self.isSpeedSendON)
      self.isPositionSendON = bool(self.isPositionSendON)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3B().pack(_x.isSpeedSendON, _x.isPositionSendON, _x.frequency))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.isSpeedSendON, _x.isPositionSendON, _x.frequency,) = _get_struct_3B().unpack(str[start:end])
      self.isSpeedSendON = bool(self.isSpeedSendON)
      self.isPositionSendON = bool(self.isPositionSendON)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3B = None
def _get_struct_3B():
    global _struct_3B
    if _struct_3B is None:
        _struct_3B = struct.Struct("<3B")
    return _struct_3B
