# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from minik_ros_wrapper/minikGetButtonMsg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class minikGetButtonMsg(genpy.Message):
  _md5sum = "3853358d8e2e329f368156066a21f0b2"
  _type = "minik_ros_wrapper/minikGetButtonMsg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# Minik Get Button Message

bool isButton1Pressed
bool isButton2Pressed
bool isButton3Pressed
"""
  __slots__ = ['isButton1Pressed','isButton2Pressed','isButton3Pressed']
  _slot_types = ['bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       isButton1Pressed,isButton2Pressed,isButton3Pressed

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(minikGetButtonMsg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.isButton1Pressed is None:
        self.isButton1Pressed = False
      if self.isButton2Pressed is None:
        self.isButton2Pressed = False
      if self.isButton3Pressed is None:
        self.isButton3Pressed = False
    else:
      self.isButton1Pressed = False
      self.isButton2Pressed = False
      self.isButton3Pressed = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3B().pack(_x.isButton1Pressed, _x.isButton2Pressed, _x.isButton3Pressed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.isButton1Pressed, _x.isButton2Pressed, _x.isButton3Pressed,) = _get_struct_3B().unpack(str[start:end])
      self.isButton1Pressed = bool(self.isButton1Pressed)
      self.isButton2Pressed = bool(self.isButton2Pressed)
      self.isButton3Pressed = bool(self.isButton3Pressed)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3B().pack(_x.isButton1Pressed, _x.isButton2Pressed, _x.isButton3Pressed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 3
      (_x.isButton1Pressed, _x.isButton2Pressed, _x.isButton3Pressed,) = _get_struct_3B().unpack(str[start:end])
      self.isButton1Pressed = bool(self.isButton1Pressed)
      self.isButton2Pressed = bool(self.isButton2Pressed)
      self.isButton3Pressed = bool(self.isButton3Pressed)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3B = None
def _get_struct_3B():
    global _struct_3B
    if _struct_3B is None:
        _struct_3B = struct.Struct("<3B")
    return _struct_3B
