# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from minik_ros_wrapper/minikGetPIDPositionMsg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class minikGetPIDPositionMsg(genpy.Message):
  _md5sum = "e7ffde16b01cf7c9fd96dfa04f0bfdc6"
  _type = "minik_ros_wrapper/minikGetPIDPositionMsg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# Minik Get Position PID Message

int32 motorID
char P
char I
char D
"""
  __slots__ = ['motorID','P','I','D']
  _slot_types = ['int32','char','char','char']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       motorID,P,I,D

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(minikGetPIDPositionMsg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.motorID is None:
        self.motorID = 0
      if self.P is None:
        self.P = 0
      if self.I is None:
        self.I = 0
      if self.D is None:
        self.D = 0
    else:
      self.motorID = 0
      self.P = 0
      self.I = 0
      self.D = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_i3B().pack(_x.motorID, _x.P, _x.I, _x.D))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 7
      (_x.motorID, _x.P, _x.I, _x.D,) = _get_struct_i3B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_i3B().pack(_x.motorID, _x.P, _x.I, _x.D))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 7
      (_x.motorID, _x.P, _x.I, _x.D,) = _get_struct_i3B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i3B = None
def _get_struct_i3B():
    global _struct_i3B
    if _struct_i3B is None:
        _struct_i3B = struct.Struct("<i3B")
    return _struct_i3B
