# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ISLH_msgs/cmd2LeadersMessage.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class cmd2LeadersMessage(genpy.Message):
  _md5sum = "dea84c50c103ccf3d723b1874cc1b015"
  _type = "ISLH_msgs/cmd2LeadersMessage"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# The task's information from coalition leader

uint16[] leaderRobotID #robot id to which the message will be sent 

uint64 sendingTime #The sending time

uint16[] messageTypeID

string[] message
"""
  __slots__ = ['leaderRobotID','sendingTime','messageTypeID','message']
  _slot_types = ['uint16[]','uint64','uint16[]','string[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       leaderRobotID,sendingTime,messageTypeID,message

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(cmd2LeadersMessage, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.leaderRobotID is None:
        self.leaderRobotID = []
      if self.sendingTime is None:
        self.sendingTime = 0
      if self.messageTypeID is None:
        self.messageTypeID = []
      if self.message is None:
        self.message = []
    else:
      self.leaderRobotID = []
      self.sendingTime = 0
      self.messageTypeID = []
      self.message = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.leaderRobotID)
      buff.write(_struct_I.pack(length))
      pattern = '<%sH'%length
      buff.write(struct.pack(pattern, *self.leaderRobotID))
      buff.write(_get_struct_Q().pack(self.sendingTime))
      length = len(self.messageTypeID)
      buff.write(_struct_I.pack(length))
      pattern = '<%sH'%length
      buff.write(struct.pack(pattern, *self.messageTypeID))
      length = len(self.message)
      buff.write(_struct_I.pack(length))
      for val1 in self.message:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.pack('<I%ss'%length, length, val1))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sH'%length
      start = end
      end += struct.calcsize(pattern)
      self.leaderRobotID = struct.unpack(pattern, str[start:end])
      start = end
      end += 8
      (self.sendingTime,) = _get_struct_Q().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sH'%length
      start = end
      end += struct.calcsize(pattern)
      self.messageTypeID = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.message = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8')
        else:
          val1 = str[start:end]
        self.message.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.leaderRobotID)
      buff.write(_struct_I.pack(length))
      pattern = '<%sH'%length
      buff.write(self.leaderRobotID.tostring())
      buff.write(_get_struct_Q().pack(self.sendingTime))
      length = len(self.messageTypeID)
      buff.write(_struct_I.pack(length))
      pattern = '<%sH'%length
      buff.write(self.messageTypeID.tostring())
      length = len(self.message)
      buff.write(_struct_I.pack(length))
      for val1 in self.message:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.pack('<I%ss'%length, length, val1))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sH'%length
      start = end
      end += struct.calcsize(pattern)
      self.leaderRobotID = numpy.frombuffer(str[start:end], dtype=numpy.uint16, count=length)
      start = end
      end += 8
      (self.sendingTime,) = _get_struct_Q().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sH'%length
      start = end
      end += struct.calcsize(pattern)
      self.messageTypeID = numpy.frombuffer(str[start:end], dtype=numpy.uint16, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.message = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8')
        else:
          val1 = str[start:end]
        self.message.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_Q = None
def _get_struct_Q():
    global _struct_Q
    if _struct_Q is None:
        _struct_Q = struct.Struct("<Q")
    return _struct_Q
