# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ISLH_msgs/cmdFromLeaderMessage.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class cmdFromLeaderMessage(genpy.Message):
  _md5sum = "49939506eb789fd4a67d4e6e601d80df"
  _type = "ISLH_msgs/cmdFromLeaderMessage"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# The incoming command message from coalition leader

uint64 sendingTime #The sending time

uint16 cmdTypeID

string cmdMessage
"""
  __slots__ = ['sendingTime','cmdTypeID','cmdMessage']
  _slot_types = ['uint64','uint16','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       sendingTime,cmdTypeID,cmdMessage

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(cmdFromLeaderMessage, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.sendingTime is None:
        self.sendingTime = 0
      if self.cmdTypeID is None:
        self.cmdTypeID = 0
      if self.cmdMessage is None:
        self.cmdMessage = ''
    else:
      self.sendingTime = 0
      self.cmdTypeID = 0
      self.cmdMessage = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_QH().pack(_x.sendingTime, _x.cmdTypeID))
      _x = self.cmdMessage
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.sendingTime, _x.cmdTypeID,) = _get_struct_QH().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.cmdMessage = str[start:end].decode('utf-8')
      else:
        self.cmdMessage = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_QH().pack(_x.sendingTime, _x.cmdTypeID))
      _x = self.cmdMessage
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.sendingTime, _x.cmdTypeID,) = _get_struct_QH().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.cmdMessage = str[start:end].decode('utf-8')
      else:
        self.cmdMessage = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_QH = None
def _get_struct_QH():
    global _struct_QH
    if _struct_QH is None:
        _struct_QH = struct.Struct("<QH")
    return _struct_QH
