# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ISLH_msgs/taskInfo2LeaderMessage.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class taskInfo2LeaderMessage(genpy.Message):
  _md5sum = "82ae7f2094f3ad6336bc9486736c3f49"
  _type = "ISLH_msgs/taskInfo2LeaderMessage"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# The task's information to coalition leader

uint64 sendingTime #The sending time

uint16 receiverRobotID #robot id to which the message will be sent 

uint16 senderRobotID #robot id which encounters the task

uint16 infoMessageType

string taskUUID # the task's UUID

uint64 encounteringTime #The encountering time in timestamp format

uint64 reachingTime # The time when the robot reached to the task site

uint16 handlingDuration

uint16 timeOutDuration

string requiredResources # Required resources for this task

float32 posX # The position of the task at x direction 
float32 posY # The position of the task at y direction 
"""
  __slots__ = ['sendingTime','receiverRobotID','senderRobotID','infoMessageType','taskUUID','encounteringTime','reachingTime','handlingDuration','timeOutDuration','requiredResources','posX','posY']
  _slot_types = ['uint64','uint16','uint16','uint16','string','uint64','uint64','uint16','uint16','string','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       sendingTime,receiverRobotID,senderRobotID,infoMessageType,taskUUID,encounteringTime,reachingTime,handlingDuration,timeOutDuration,requiredResources,posX,posY

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(taskInfo2LeaderMessage, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.sendingTime is None:
        self.sendingTime = 0
      if self.receiverRobotID is None:
        self.receiverRobotID = 0
      if self.senderRobotID is None:
        self.senderRobotID = 0
      if self.infoMessageType is None:
        self.infoMessageType = 0
      if self.taskUUID is None:
        self.taskUUID = ''
      if self.encounteringTime is None:
        self.encounteringTime = 0
      if self.reachingTime is None:
        self.reachingTime = 0
      if self.handlingDuration is None:
        self.handlingDuration = 0
      if self.timeOutDuration is None:
        self.timeOutDuration = 0
      if self.requiredResources is None:
        self.requiredResources = ''
      if self.posX is None:
        self.posX = 0.
      if self.posY is None:
        self.posY = 0.
    else:
      self.sendingTime = 0
      self.receiverRobotID = 0
      self.senderRobotID = 0
      self.infoMessageType = 0
      self.taskUUID = ''
      self.encounteringTime = 0
      self.reachingTime = 0
      self.handlingDuration = 0
      self.timeOutDuration = 0
      self.requiredResources = ''
      self.posX = 0.
      self.posY = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_Q3H().pack(_x.sendingTime, _x.receiverRobotID, _x.senderRobotID, _x.infoMessageType))
      _x = self.taskUUID
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2Q2H().pack(_x.encounteringTime, _x.reachingTime, _x.handlingDuration, _x.timeOutDuration))
      _x = self.requiredResources
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2f().pack(_x.posX, _x.posY))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 14
      (_x.sendingTime, _x.receiverRobotID, _x.senderRobotID, _x.infoMessageType,) = _get_struct_Q3H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.taskUUID = str[start:end].decode('utf-8')
      else:
        self.taskUUID = str[start:end]
      _x = self
      start = end
      end += 20
      (_x.encounteringTime, _x.reachingTime, _x.handlingDuration, _x.timeOutDuration,) = _get_struct_2Q2H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.requiredResources = str[start:end].decode('utf-8')
      else:
        self.requiredResources = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.posX, _x.posY,) = _get_struct_2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_Q3H().pack(_x.sendingTime, _x.receiverRobotID, _x.senderRobotID, _x.infoMessageType))
      _x = self.taskUUID
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2Q2H().pack(_x.encounteringTime, _x.reachingTime, _x.handlingDuration, _x.timeOutDuration))
      _x = self.requiredResources
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2f().pack(_x.posX, _x.posY))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 14
      (_x.sendingTime, _x.receiverRobotID, _x.senderRobotID, _x.infoMessageType,) = _get_struct_Q3H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.taskUUID = str[start:end].decode('utf-8')
      else:
        self.taskUUID = str[start:end]
      _x = self
      start = end
      end += 20
      (_x.encounteringTime, _x.reachingTime, _x.handlingDuration, _x.timeOutDuration,) = _get_struct_2Q2H().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.requiredResources = str[start:end].decode('utf-8')
      else:
        self.requiredResources = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.posX, _x.posY,) = _get_struct_2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2Q2H = None
def _get_struct_2Q2H():
    global _struct_2Q2H
    if _struct_2Q2H is None:
        _struct_2Q2H = struct.Struct("<2Q2H")
    return _struct_2Q2H
_struct_2f = None
def _get_struct_2f():
    global _struct_2f
    if _struct_2f is None:
        _struct_2f = struct.Struct("<2f")
    return _struct_2f
_struct_Q3H = None
def _get_struct_Q3H():
    global _struct_Q3H
    if _struct_Q3H is None:
        _struct_Q3H = struct.Struct("<Q3H")
    return _struct_Q3H
