(cl:in-package ISLH_msgs-msg)
(cl:export '(SENDINGTIME-VAL
          SENDINGTIME
          INFOTYPEID-VAL
          INFOTYPEID
          SENDERROBOTID-VAL
          SENDERROBOTID
          ENCOUNTERINGROBOTID-VAL
          ENCOUNTERINGROBOTID
          ENCOUNTERINGTIME-VAL
          ENCOUNTERINGTIME
          STARTHANDLINGTIME-VAL
          STARTHANDLINGTIME
          HANDLINGDURATION-VAL
          HANDLINGDURATION
          TIMEOUTDURATION-VAL
          TIMEOUTDURATION
          REQUIREDRESOURCES-VAL
          REQUIREDRESOURCES
          POSX-VAL
          POSX
          POSY-VAL
          POSY
          TASKUUID-VAL
          TASKUUID
          EXTRAMSG-VAL
          EXTRAMSG
))