(cl:in-package ISLH_msgs-msg)
(cl:export '(TASKUUID-VAL
          TASKUUID
          ENCOUNTERINGROBOTID-VAL
          ENCOUNTERINGROBOTID
          RESPONSIBLEUNIT-VAL
          RESPONSIBLEUNIT
          ENCOUNTERINGTIME-VAL
          ENCOUNTERINGTIME
          STARTHANDLINGTIME-VAL
          STARTHANDLINGTIME
          POSXY-VAL
          POSXY
          TASKRESOURCE-VAL
          TASKRESOURCE
          HANDLINGDURATION-VAL
          HANDLINGDURATION
          TIMEOUTDURATION-VAL
          TIMEOUTDURATION
          STATUS-VAL
          STATUS
          TASKSITERADIUS-VAL
          TASKSITERADIUS
))