(cl:in-package ISLH_msgs-msg)
(cl:export '(TASKUUID-VAL
          TASKUUID
          TIMESTAMP-VAL
          TIMESTAMP
          HANDLINGDURATION-VAL
          HANDLINGDURATION
          TIMEOUTDURATION-VAL
          TIMEOUTDURATION
          REQUIREDRESOURCES-VAL
          REQUIREDRESOURCES
))