(cl:in-package ISLH_msgs-msg)
(cl:export '(SENDERROBOTID-VAL
          SENDERROBOTID
          INFOMESSAGETYPE-VAL
          INFOMESSAGETYPE
          TASKUUID-VAL
          TASKUUID
          ENCOUNTERINGTIME-VAL
          ENCOUNTERINGTIME
          REACHINGTIME-VAL
          REACHINGTIME
          HANDLINGDURATION-VAL
          HANDLINGDURATION
          TIMEOUTDURATION-VAL
          TIMEOUTDURATION
          REQUIREDRESOURCES-VAL
          REQUIREDRESOURCES
          POSX-VAL
          POSX
          POSY-VAL
          POSY
))