goal_topology: [0, 1, 0, 0, 0,
                1, 0, 0, 0, 0,
                0, 0, 0, 1, 0,
                0, 0, 1, 0, 1,
                0, 0, 0, 1, 0]
ro_ij: 0.5
k: 6
threshold: 3
quite_mode: true
print_fi_b_dot: false
print_distances: true
print_eta: false
print_fi_eta_dot: false
yaml_file_name: "/home/berkay/catkin_ws/src/realization/results/goal3_noise05_results.yaml"
