// Generated by gencpp from file ISLH_msgs/cmd2RobotsFromLeaderMessage.msg
// DO NOT EDIT!


#ifndef ISLH_MSGS_MESSAGE_CMD2ROBOTSFROMLEADERMESSAGE_H
#define ISLH_MSGS_MESSAGE_CMD2ROBOTSFROMLEADERMESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ISLH_msgs
{
template <class ContainerAllocator>
struct cmd2RobotsFromLeaderMessage_
{
  typedef cmd2RobotsFromLeaderMessage_<ContainerAllocator> Type;

  cmd2RobotsFromLeaderMessage_()
    : receiverRobotID()
    , sendingTime(0)
    , cmdTypeID(0)
    , cmdMessage()  {
    }
  cmd2RobotsFromLeaderMessage_(const ContainerAllocator& _alloc)
    : receiverRobotID(_alloc)
    , sendingTime(0)
    , cmdTypeID(0)
    , cmdMessage(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint16_t, typename ContainerAllocator::template rebind<uint16_t>::other >  _receiverRobotID_type;
  _receiverRobotID_type receiverRobotID;

   typedef uint64_t _sendingTime_type;
  _sendingTime_type sendingTime;

   typedef uint16_t _cmdTypeID_type;
  _cmdTypeID_type cmdTypeID;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _cmdMessage_type;
  _cmdMessage_type cmdMessage;





  typedef boost::shared_ptr< ::ISLH_msgs::cmd2RobotsFromLeaderMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ISLH_msgs::cmd2RobotsFromLeaderMessage_<ContainerAllocator> const> ConstPtr;

}; // struct cmd2RobotsFromLeaderMessage_

typedef ::ISLH_msgs::cmd2RobotsFromLeaderMessage_<std::allocator<void> > cmd2RobotsFromLeaderMessage;

typedef boost::shared_ptr< ::ISLH_msgs::cmd2RobotsFromLeaderMessage > cmd2RobotsFromLeaderMessagePtr;
typedef boost::shared_ptr< ::ISLH_msgs::cmd2RobotsFromLeaderMessage const> cmd2RobotsFromLeaderMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ISLH_msgs::cmd2RobotsFromLeaderMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ISLH_msgs::cmd2RobotsFromLeaderMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ISLH_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ISLH_msgs': ['/home/berkay/catkin_ws/src/ISLH_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ISLH_msgs::cmd2RobotsFromLeaderMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ISLH_msgs::cmd2RobotsFromLeaderMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ISLH_msgs::cmd2RobotsFromLeaderMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ISLH_msgs::cmd2RobotsFromLeaderMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ISLH_msgs::cmd2RobotsFromLeaderMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ISLH_msgs::cmd2RobotsFromLeaderMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ISLH_msgs::cmd2RobotsFromLeaderMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "56a7753bb3b7a241e2936846abb3f9d4";
  }

  static const char* value(const ::ISLH_msgs::cmd2RobotsFromLeaderMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x56a7753bb3b7a241ULL;
  static const uint64_t static_value2 = 0xe2936846abb3f9d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::ISLH_msgs::cmd2RobotsFromLeaderMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ISLH_msgs/cmd2RobotsFromLeaderMessage";
  }

  static const char* value(const ::ISLH_msgs::cmd2RobotsFromLeaderMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ISLH_msgs::cmd2RobotsFromLeaderMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# The outgoing command message from coalition leader\n\
\n\
uint16[] receiverRobotID\n\
\n\
uint64 sendingTime #The sending time\n\
\n\
uint16 cmdTypeID\n\
\n\
string cmdMessage\n\
";
  }

  static const char* value(const ::ISLH_msgs::cmd2RobotsFromLeaderMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ISLH_msgs::cmd2RobotsFromLeaderMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.receiverRobotID);
      stream.next(m.sendingTime);
      stream.next(m.cmdTypeID);
      stream.next(m.cmdMessage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cmd2RobotsFromLeaderMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ISLH_msgs::cmd2RobotsFromLeaderMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ISLH_msgs::cmd2RobotsFromLeaderMessage_<ContainerAllocator>& v)
  {
    s << indent << "receiverRobotID[]" << std::endl;
    for (size_t i = 0; i < v.receiverRobotID.size(); ++i)
    {
      s << indent << "  receiverRobotID[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.receiverRobotID[i]);
    }
    s << indent << "sendingTime: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.sendingTime);
    s << indent << "cmdTypeID: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.cmdTypeID);
    s << indent << "cmdMessage: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.cmdMessage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ISLH_MSGS_MESSAGE_CMD2ROBOTSFROMLEADERMESSAGE_H
