// Generated by gencpp from file ISLH_msgs/cmdFromLeaderMessage.msg
// DO NOT EDIT!


#ifndef ISLH_MSGS_MESSAGE_CMDFROMLEADERMESSAGE_H
#define ISLH_MSGS_MESSAGE_CMDFROMLEADERMESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ISLH_msgs
{
template <class ContainerAllocator>
struct cmdFromLeaderMessage_
{
  typedef cmdFromLeaderMessage_<ContainerAllocator> Type;

  cmdFromLeaderMessage_()
    : sendingTime(0)
    , cmdTypeID(0)
    , cmdMessage()  {
    }
  cmdFromLeaderMessage_(const ContainerAllocator& _alloc)
    : sendingTime(0)
    , cmdTypeID(0)
    , cmdMessage(_alloc)  {
  (void)_alloc;
    }



   typedef uint64_t _sendingTime_type;
  _sendingTime_type sendingTime;

   typedef uint16_t _cmdTypeID_type;
  _cmdTypeID_type cmdTypeID;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _cmdMessage_type;
  _cmdMessage_type cmdMessage;





  typedef boost::shared_ptr< ::ISLH_msgs::cmdFromLeaderMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ISLH_msgs::cmdFromLeaderMessage_<ContainerAllocator> const> ConstPtr;

}; // struct cmdFromLeaderMessage_

typedef ::ISLH_msgs::cmdFromLeaderMessage_<std::allocator<void> > cmdFromLeaderMessage;

typedef boost::shared_ptr< ::ISLH_msgs::cmdFromLeaderMessage > cmdFromLeaderMessagePtr;
typedef boost::shared_ptr< ::ISLH_msgs::cmdFromLeaderMessage const> cmdFromLeaderMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ISLH_msgs::cmdFromLeaderMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ISLH_msgs::cmdFromLeaderMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ISLH_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ISLH_msgs': ['/home/berkay/catkin_ws/src/ISLH_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ISLH_msgs::cmdFromLeaderMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ISLH_msgs::cmdFromLeaderMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ISLH_msgs::cmdFromLeaderMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ISLH_msgs::cmdFromLeaderMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ISLH_msgs::cmdFromLeaderMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ISLH_msgs::cmdFromLeaderMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ISLH_msgs::cmdFromLeaderMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "49939506eb789fd4a67d4e6e601d80df";
  }

  static const char* value(const ::ISLH_msgs::cmdFromLeaderMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x49939506eb789fd4ULL;
  static const uint64_t static_value2 = 0xa67d4e6e601d80dfULL;
};

template<class ContainerAllocator>
struct DataType< ::ISLH_msgs::cmdFromLeaderMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ISLH_msgs/cmdFromLeaderMessage";
  }

  static const char* value(const ::ISLH_msgs::cmdFromLeaderMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ISLH_msgs::cmdFromLeaderMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# The incoming command message from coalition leader\n\
\n\
uint64 sendingTime #The sending time\n\
\n\
uint16 cmdTypeID\n\
\n\
string cmdMessage\n\
";
  }

  static const char* value(const ::ISLH_msgs::cmdFromLeaderMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ISLH_msgs::cmdFromLeaderMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sendingTime);
      stream.next(m.cmdTypeID);
      stream.next(m.cmdMessage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cmdFromLeaderMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ISLH_msgs::cmdFromLeaderMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ISLH_msgs::cmdFromLeaderMessage_<ContainerAllocator>& v)
  {
    s << indent << "sendingTime: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.sendingTime);
    s << indent << "cmdTypeID: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.cmdTypeID);
    s << indent << "cmdMessage: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.cmdMessage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ISLH_MSGS_MESSAGE_CMDFROMLEADERMESSAGE_H
