// Generated by gencpp from file ISLH_msgs/cmdFromCoordinatorMessage.msg
// DO NOT EDIT!


#ifndef ISLH_MSGS_MESSAGE_CMDFROMCOORDINATORMESSAGE_H
#define ISLH_MSGS_MESSAGE_CMDFROMCOORDINATORMESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ISLH_msgs
{
template <class ContainerAllocator>
struct cmdFromCoordinatorMessage_
{
  typedef cmdFromCoordinatorMessage_<ContainerAllocator> Type;

  cmdFromCoordinatorMessage_()
    : sendingTime(0)
    , messageTypeID(0)
    , message()  {
    }
  cmdFromCoordinatorMessage_(const ContainerAllocator& _alloc)
    : sendingTime(0)
    , messageTypeID(0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint64_t _sendingTime_type;
  _sendingTime_type sendingTime;

   typedef uint16_t _messageTypeID_type;
  _messageTypeID_type messageTypeID;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::ISLH_msgs::cmdFromCoordinatorMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ISLH_msgs::cmdFromCoordinatorMessage_<ContainerAllocator> const> ConstPtr;

}; // struct cmdFromCoordinatorMessage_

typedef ::ISLH_msgs::cmdFromCoordinatorMessage_<std::allocator<void> > cmdFromCoordinatorMessage;

typedef boost::shared_ptr< ::ISLH_msgs::cmdFromCoordinatorMessage > cmdFromCoordinatorMessagePtr;
typedef boost::shared_ptr< ::ISLH_msgs::cmdFromCoordinatorMessage const> cmdFromCoordinatorMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ISLH_msgs::cmdFromCoordinatorMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ISLH_msgs::cmdFromCoordinatorMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ISLH_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ISLH_msgs': ['/home/berkay/catkin_ws/src/ISLH_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ISLH_msgs::cmdFromCoordinatorMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ISLH_msgs::cmdFromCoordinatorMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ISLH_msgs::cmdFromCoordinatorMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ISLH_msgs::cmdFromCoordinatorMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ISLH_msgs::cmdFromCoordinatorMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ISLH_msgs::cmdFromCoordinatorMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ISLH_msgs::cmdFromCoordinatorMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6b00d2e721f211550b5ec2a337817798";
  }

  static const char* value(const ::ISLH_msgs::cmdFromCoordinatorMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6b00d2e721f21155ULL;
  static const uint64_t static_value2 = 0x0b5ec2a337817798ULL;
};

template<class ContainerAllocator>
struct DataType< ::ISLH_msgs::cmdFromCoordinatorMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ISLH_msgs/cmdFromCoordinatorMessage";
  }

  static const char* value(const ::ISLH_msgs::cmdFromCoordinatorMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ISLH_msgs::cmdFromCoordinatorMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# The incoming command message from the coordinator\n\
\n\
uint64 sendingTime #The sending time\n\
\n\
uint16 messageTypeID\n\
\n\
string message\n\
";
  }

  static const char* value(const ::ISLH_msgs::cmdFromCoordinatorMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ISLH_msgs::cmdFromCoordinatorMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sendingTime);
      stream.next(m.messageTypeID);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cmdFromCoordinatorMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ISLH_msgs::cmdFromCoordinatorMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ISLH_msgs::cmdFromCoordinatorMessage_<ContainerAllocator>& v)
  {
    s << indent << "sendingTime: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.sendingTime);
    s << indent << "messageTypeID: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.messageTypeID);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ISLH_MSGS_MESSAGE_CMDFROMCOORDINATORMESSAGE_H
