// Generated by gencpp from file ISLH_msgs/inMessage.msg
// DO NOT EDIT!


#ifndef ISLH_MSGS_MESSAGE_INMESSAGE_H
#define ISLH_MSGS_MESSAGE_INMESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ISLH_msgs
{
template <class ContainerAllocator>
struct inMessage_
{
  typedef inMessage_<ContainerAllocator> Type;

  inMessage_()
    : robotid(0)
    , messageid(0)
    , message()  {
    }
  inMessage_(const ContainerAllocator& _alloc)
    : robotid(0)
    , messageid(0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint16_t _robotid_type;
  _robotid_type robotid;

   typedef uint16_t _messageid_type;
  _messageid_type messageid;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::ISLH_msgs::inMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ISLH_msgs::inMessage_<ContainerAllocator> const> ConstPtr;

}; // struct inMessage_

typedef ::ISLH_msgs::inMessage_<std::allocator<void> > inMessage;

typedef boost::shared_ptr< ::ISLH_msgs::inMessage > inMessagePtr;
typedef boost::shared_ptr< ::ISLH_msgs::inMessage const> inMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ISLH_msgs::inMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ISLH_msgs::inMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ISLH_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ISLH_msgs': ['/home/berkay/catkin_ws/src/ISLH_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ISLH_msgs::inMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ISLH_msgs::inMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ISLH_msgs::inMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ISLH_msgs::inMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ISLH_msgs::inMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ISLH_msgs::inMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ISLH_msgs::inMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "29816f7dd48299059674f73ccfcba3d5";
  }

  static const char* value(const ::ISLH_msgs::inMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x29816f7dd4829905ULL;
  static const uint64_t static_value2 = 0x9674f73ccfcba3d5ULL;
};

template<class ContainerAllocator>
struct DataType< ::ISLH_msgs::inMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ISLH_msgs/inMessage";
  }

  static const char* value(const ::ISLH_msgs::inMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ISLH_msgs::inMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Incoming messages\n\
\n\
uint16 robotid #sender id\n\
\n\
uint16 messageid\n\
\n\
string message #message\n\
";
  }

  static const char* value(const ::ISLH_msgs::inMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ISLH_msgs::inMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robotid);
      stream.next(m.messageid);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct inMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ISLH_msgs::inMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ISLH_msgs::inMessage_<ContainerAllocator>& v)
  {
    s << indent << "robotid: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.robotid);
    s << indent << "messageid: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.messageid);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ISLH_MSGS_MESSAGE_INMESSAGE_H
