// Generated by gencpp from file ISLH_msgs/newTaskInfoMessage.msg
// DO NOT EDIT!


#ifndef ISLH_MSGS_MESSAGE_NEWTASKINFOMESSAGE_H
#define ISLH_MSGS_MESSAGE_NEWTASKINFOMESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ISLH_msgs
{
template <class ContainerAllocator>
struct newTaskInfoMessage_
{
  typedef newTaskInfoMessage_<ContainerAllocator> Type;

  newTaskInfoMessage_()
    : taskUUID()
    , timeStamp(0)
    , handlingDuration(0)
    , timeOutDuration(0)
    , requiredResources()  {
    }
  newTaskInfoMessage_(const ContainerAllocator& _alloc)
    : taskUUID(_alloc)
    , timeStamp(0)
    , handlingDuration(0)
    , timeOutDuration(0)
    , requiredResources(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _taskUUID_type;
  _taskUUID_type taskUUID;

   typedef uint64_t _timeStamp_type;
  _timeStamp_type timeStamp;

   typedef uint16_t _handlingDuration_type;
  _handlingDuration_type handlingDuration;

   typedef uint16_t _timeOutDuration_type;
  _timeOutDuration_type timeOutDuration;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _requiredResources_type;
  _requiredResources_type requiredResources;





  typedef boost::shared_ptr< ::ISLH_msgs::newTaskInfoMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ISLH_msgs::newTaskInfoMessage_<ContainerAllocator> const> ConstPtr;

}; // struct newTaskInfoMessage_

typedef ::ISLH_msgs::newTaskInfoMessage_<std::allocator<void> > newTaskInfoMessage;

typedef boost::shared_ptr< ::ISLH_msgs::newTaskInfoMessage > newTaskInfoMessagePtr;
typedef boost::shared_ptr< ::ISLH_msgs::newTaskInfoMessage const> newTaskInfoMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ISLH_msgs::newTaskInfoMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ISLH_msgs::newTaskInfoMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ISLH_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ISLH_msgs': ['/home/berkay/catkin_ws/src/ISLH_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ISLH_msgs::newTaskInfoMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ISLH_msgs::newTaskInfoMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ISLH_msgs::newTaskInfoMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ISLH_msgs::newTaskInfoMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ISLH_msgs::newTaskInfoMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ISLH_msgs::newTaskInfoMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ISLH_msgs::newTaskInfoMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0857da229f3a63b6ca6a5f69dd323a29";
  }

  static const char* value(const ::ISLH_msgs::newTaskInfoMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0857da229f3a63b6ULL;
  static const uint64_t static_value2 = 0xca6a5f69dd323a29ULL;
};

template<class ContainerAllocator>
struct DataType< ::ISLH_msgs::newTaskInfoMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ISLH_msgs/newTaskInfoMessage";
  }

  static const char* value(const ::ISLH_msgs::newTaskInfoMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ISLH_msgs::newTaskInfoMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# New task's information\n\
\n\
string taskUUID # Universally Unique Identifier (UUID)\n\
\n\
uint64 timeStamp #The encountering time\n\
\n\
uint16 handlingDuration\n\
\n\
uint16 timeOutDuration\n\
\n\
string requiredResources # Required resources for this task\n\
\n\
";
  }

  static const char* value(const ::ISLH_msgs::newTaskInfoMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ISLH_msgs::newTaskInfoMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.taskUUID);
      stream.next(m.timeStamp);
      stream.next(m.handlingDuration);
      stream.next(m.timeOutDuration);
      stream.next(m.requiredResources);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct newTaskInfoMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ISLH_msgs::newTaskInfoMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ISLH_msgs::newTaskInfoMessage_<ContainerAllocator>& v)
  {
    s << indent << "taskUUID: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.taskUUID);
    s << indent << "timeStamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timeStamp);
    s << indent << "handlingDuration: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.handlingDuration);
    s << indent << "timeOutDuration: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.timeOutDuration);
    s << indent << "requiredResources: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.requiredResources);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ISLH_MSGS_MESSAGE_NEWTASKINFOMESSAGE_H
