// Generated by gencpp from file ISLH_msgs/outMessage.msg
// DO NOT EDIT!


#ifndef ISLH_MSGS_MESSAGE_OUTMESSAGE_H
#define ISLH_MSGS_MESSAGE_OUTMESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ISLH_msgs
{
template <class ContainerAllocator>
struct outMessage_
{
  typedef outMessage_<ContainerAllocator> Type;

  outMessage_()
    : robotid()
    , messageTypeID()
    , messageIndx()
    , message()  {
    }
  outMessage_(const ContainerAllocator& _alloc)
    : robotid(_alloc)
    , messageTypeID(_alloc)
    , messageIndx(_alloc)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint16_t, typename ContainerAllocator::template rebind<uint16_t>::other >  _robotid_type;
  _robotid_type robotid;

   typedef std::vector<uint16_t, typename ContainerAllocator::template rebind<uint16_t>::other >  _messageTypeID_type;
  _messageTypeID_type messageTypeID;

   typedef std::vector<uint16_t, typename ContainerAllocator::template rebind<uint16_t>::other >  _messageIndx_type;
  _messageIndx_type messageIndx;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::ISLH_msgs::outMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ISLH_msgs::outMessage_<ContainerAllocator> const> ConstPtr;

}; // struct outMessage_

typedef ::ISLH_msgs::outMessage_<std::allocator<void> > outMessage;

typedef boost::shared_ptr< ::ISLH_msgs::outMessage > outMessagePtr;
typedef boost::shared_ptr< ::ISLH_msgs::outMessage const> outMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ISLH_msgs::outMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ISLH_msgs::outMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ISLH_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ISLH_msgs': ['/home/berkay/catkin_ws/src/ISLH_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ISLH_msgs::outMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ISLH_msgs::outMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ISLH_msgs::outMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ISLH_msgs::outMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ISLH_msgs::outMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ISLH_msgs::outMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ISLH_msgs::outMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8e9310b478059d7c506189771b569d0d";
  }

  static const char* value(const ::ISLH_msgs::outMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8e9310b478059d7cULL;
  static const uint64_t static_value2 = 0x506189771b569d0dULL;
};

template<class ContainerAllocator>
struct DataType< ::ISLH_msgs::outMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ISLH_msgs/outMessage";
  }

  static const char* value(const ::ISLH_msgs::outMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ISLH_msgs::outMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# outgoing  messages\n\
\n\
uint16[] robotid #receiver id\n\
\n\
uint16[] messageTypeID\n\
\n\
uint16[] messageIndx # which message is sent to which robot\n\
\n\
string[] message #message\n\
\n\
\n\
";
  }

  static const char* value(const ::ISLH_msgs::outMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ISLH_msgs::outMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robotid);
      stream.next(m.messageTypeID);
      stream.next(m.messageIndx);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct outMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ISLH_msgs::outMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ISLH_msgs::outMessage_<ContainerAllocator>& v)
  {
    s << indent << "robotid[]" << std::endl;
    for (size_t i = 0; i < v.robotid.size(); ++i)
    {
      s << indent << "  robotid[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.robotid[i]);
    }
    s << indent << "messageTypeID[]" << std::endl;
    for (size_t i = 0; i < v.messageTypeID.size(); ++i)
    {
      s << indent << "  messageTypeID[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.messageTypeID[i]);
    }
    s << indent << "messageIndx[]" << std::endl;
    for (size_t i = 0; i < v.messageIndx.size(); ++i)
    {
      s << indent << "  messageIndx[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.messageIndx[i]);
    }
    s << indent << "message[]" << std::endl;
    for (size_t i = 0; i < v.message.size(); ++i)
    {
      s << indent << "  message[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ISLH_MSGS_MESSAGE_OUTMESSAGE_H
