// Generated by gencpp from file ISLH_msgs/robotPose.msg
// DO NOT EDIT!


#ifndef ISLH_MSGS_MESSAGE_ROBOTPOSE_H
#define ISLH_MSGS_MESSAGE_ROBOTPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace ISLH_msgs
{
template <class ContainerAllocator>
struct robotPose_
{
  typedef robotPose_<ContainerAllocator> Type;

  robotPose_()
    : id(0)
    , position()
    , target()
    , calYaw(0.0)
    , radYaw(0.0)  {
    }
  robotPose_(const ContainerAllocator& _alloc)
    : id(0)
    , position(_alloc)
    , target(_alloc)
    , calYaw(0.0)
    , radYaw(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _target_type;
  _target_type target;

   typedef float _calYaw_type;
  _calYaw_type calYaw;

   typedef float _radYaw_type;
  _radYaw_type radYaw;





  typedef boost::shared_ptr< ::ISLH_msgs::robotPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ISLH_msgs::robotPose_<ContainerAllocator> const> ConstPtr;

}; // struct robotPose_

typedef ::ISLH_msgs::robotPose_<std::allocator<void> > robotPose;

typedef boost::shared_ptr< ::ISLH_msgs::robotPose > robotPosePtr;
typedef boost::shared_ptr< ::ISLH_msgs::robotPose const> robotPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ISLH_msgs::robotPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ISLH_msgs::robotPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ISLH_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ISLH_msgs': ['/home/berkay/catkin_ws/src/ISLH_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ISLH_msgs::robotPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ISLH_msgs::robotPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ISLH_msgs::robotPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ISLH_msgs::robotPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ISLH_msgs::robotPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ISLH_msgs::robotPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ISLH_msgs::robotPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0eef6d6e44271c92907c87eea9d5073a";
  }

  static const char* value(const ::ISLH_msgs::robotPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0eef6d6e44271c92ULL;
  static const uint64_t static_value2 = 0x907c87eea9d5073aULL;
};

template<class ContainerAllocator>
struct DataType< ::ISLH_msgs::robotPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ISLH_msgs/robotPose";
  }

  static const char* value(const ::ISLH_msgs::robotPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ISLH_msgs::robotPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#The robot's position information and target information\n\
\n\
int32 id\n\
\n\
geometry_msgs/Point position\n\
\n\
geometry_msgs/Point target\n\
\n\
float32 calYaw\n\
float32 radYaw\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::ISLH_msgs::robotPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ISLH_msgs::robotPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.position);
      stream.next(m.target);
      stream.next(m.calYaw);
      stream.next(m.radYaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robotPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ISLH_msgs::robotPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ISLH_msgs::robotPose_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "target: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.target);
    s << indent << "calYaw: ";
    Printer<float>::stream(s, indent + "  ", v.calYaw);
    s << indent << "radYaw: ";
    Printer<float>::stream(s, indent + "  ", v.radYaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ISLH_MSGS_MESSAGE_ROBOTPOSE_H
