// Generated by gencpp from file ISLH_msgs/robotPositions.msg
// DO NOT EDIT!


#ifndef ISLH_MSGS_MESSAGE_ROBOTPOSITIONS_H
#define ISLH_MSGS_MESSAGE_ROBOTPOSITIONS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace ISLH_msgs
{
template <class ContainerAllocator>
struct robotPositions_
{
  typedef robotPositions_<ContainerAllocator> Type;

  robotPositions_()
    : positions()
    , directions()  {
    }
  robotPositions_(const ContainerAllocator& _alloc)
    : positions(_alloc)
    , directions(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Pose2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose2D_<ContainerAllocator> >::other >  _positions_type;
  _positions_type positions;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _directions_type;
  _directions_type directions;





  typedef boost::shared_ptr< ::ISLH_msgs::robotPositions_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ISLH_msgs::robotPositions_<ContainerAllocator> const> ConstPtr;

}; // struct robotPositions_

typedef ::ISLH_msgs::robotPositions_<std::allocator<void> > robotPositions;

typedef boost::shared_ptr< ::ISLH_msgs::robotPositions > robotPositionsPtr;
typedef boost::shared_ptr< ::ISLH_msgs::robotPositions const> robotPositionsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ISLH_msgs::robotPositions_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ISLH_msgs::robotPositions_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ISLH_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ISLH_msgs': ['/home/berkay/catkin_ws/src/ISLH_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ISLH_msgs::robotPositions_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ISLH_msgs::robotPositions_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ISLH_msgs::robotPositions_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ISLH_msgs::robotPositions_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ISLH_msgs::robotPositions_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ISLH_msgs::robotPositions_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ISLH_msgs::robotPositions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b8470ea0d581e5724ea0df486cf9d5a";
  }

  static const char* value(const ::ISLH_msgs::robotPositions_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b8470ea0d581e57ULL;
  static const uint64_t static_value2 = 0x24ea0df486cf9d5aULL;
};

template<class ContainerAllocator>
struct DataType< ::ISLH_msgs::robotPositions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ISLH_msgs/robotPositions";
  }

  static const char* value(const ::ISLH_msgs::robotPositions_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ISLH_msgs::robotPositions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#The robots' position information\n\
\n\
geometry_msgs/Pose2D[] positions\n\
\n\
float32[] directions\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# Deprecated\n\
# Please use the full 3D pose.\n\
\n\
# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n\
\n\
# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n\
\n\
\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::ISLH_msgs::robotPositions_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ISLH_msgs::robotPositions_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.positions);
      stream.next(m.directions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robotPositions_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ISLH_msgs::robotPositions_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ISLH_msgs::robotPositions_<ContainerAllocator>& v)
  {
    s << indent << "positions[]" << std::endl;
    for (size_t i = 0; i < v.positions.size(); ++i)
    {
      s << indent << "  positions[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "    ", v.positions[i]);
    }
    s << indent << "directions[]" << std::endl;
    for (size_t i = 0; i < v.directions.size(); ++i)
    {
      s << indent << "  directions[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.directions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ISLH_MSGS_MESSAGE_ROBOTPOSITIONS_H
