// Generated by gencpp from file ISLH_msgs/targetPoseListMessage.msg
// DO NOT EDIT!


#ifndef ISLH_MSGS_MESSAGE_TARGETPOSELISTMESSAGE_H
#define ISLH_MSGS_MESSAGE_TARGETPOSELISTMESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace ISLH_msgs
{
template <class ContainerAllocator>
struct targetPoseListMessage_
{
  typedef targetPoseListMessage_<ContainerAllocator> Type;

  targetPoseListMessage_()
    : robotIDs()
    , targetPoses()  {
    }
  targetPoseListMessage_(const ContainerAllocator& _alloc)
    : robotIDs(_alloc)
    , targetPoses(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint16_t, typename ContainerAllocator::template rebind<uint16_t>::other >  _robotIDs_type;
  _robotIDs_type robotIDs;

   typedef std::vector< ::geometry_msgs::Pose2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose2D_<ContainerAllocator> >::other >  _targetPoses_type;
  _targetPoses_type targetPoses;





  typedef boost::shared_ptr< ::ISLH_msgs::targetPoseListMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ISLH_msgs::targetPoseListMessage_<ContainerAllocator> const> ConstPtr;

}; // struct targetPoseListMessage_

typedef ::ISLH_msgs::targetPoseListMessage_<std::allocator<void> > targetPoseListMessage;

typedef boost::shared_ptr< ::ISLH_msgs::targetPoseListMessage > targetPoseListMessagePtr;
typedef boost::shared_ptr< ::ISLH_msgs::targetPoseListMessage const> targetPoseListMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ISLH_msgs::targetPoseListMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ISLH_msgs::targetPoseListMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ISLH_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ISLH_msgs': ['/home/berkay/catkin_ws/src/ISLH_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ISLH_msgs::targetPoseListMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ISLH_msgs::targetPoseListMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ISLH_msgs::targetPoseListMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ISLH_msgs::targetPoseListMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ISLH_msgs::targetPoseListMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ISLH_msgs::targetPoseListMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ISLH_msgs::targetPoseListMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d1b04727e448336dea593a258b3fabf6";
  }

  static const char* value(const ::ISLH_msgs::targetPoseListMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd1b04727e448336dULL;
  static const uint64_t static_value2 = 0xea593a258b3fabf6ULL;
};

template<class ContainerAllocator>
struct DataType< ::ISLH_msgs::targetPoseListMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ISLH_msgs/targetPoseListMessage";
  }

  static const char* value(const ::ISLH_msgs::targetPoseListMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ISLH_msgs::targetPoseListMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# The incoming message (target pose list) from coalition leader\n\
\n\
uint16[] robotIDs\n\
\n\
geometry_msgs/Pose2D[] targetPoses\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# Deprecated\n\
# Please use the full 3D pose.\n\
\n\
# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n\
\n\
# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n\
\n\
\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::ISLH_msgs::targetPoseListMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ISLH_msgs::targetPoseListMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robotIDs);
      stream.next(m.targetPoses);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct targetPoseListMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ISLH_msgs::targetPoseListMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ISLH_msgs::targetPoseListMessage_<ContainerAllocator>& v)
  {
    s << indent << "robotIDs[]" << std::endl;
    for (size_t i = 0; i < v.robotIDs.size(); ++i)
    {
      s << indent << "  robotIDs[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.robotIDs[i]);
    }
    s << indent << "targetPoses[]" << std::endl;
    for (size_t i = 0; i < v.targetPoses.size(); ++i)
    {
      s << indent << "  targetPoses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "    ", v.targetPoses[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ISLH_MSGS_MESSAGE_TARGETPOSELISTMESSAGE_H
