// Generated by gencpp from file ISLH_msgs/taskInfo2CoordinatorMessage.msg
// DO NOT EDIT!


#ifndef ISLH_MSGS_MESSAGE_TASKINFO2COORDINATORMESSAGE_H
#define ISLH_MSGS_MESSAGE_TASKINFO2COORDINATORMESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ISLH_msgs
{
template <class ContainerAllocator>
struct taskInfo2CoordinatorMessage_
{
  typedef taskInfo2CoordinatorMessage_<ContainerAllocator> Type;

  taskInfo2CoordinatorMessage_()
    : sendingTime(0)
    , infoTypeID(0)
    , receiverRobotID(0)
    , senderRobotID(0)
    , encounteringRobotID(0)
    , encounteringTime(0)
    , handlingDuration(0)
    , timeOutDuration(0)
    , startHandlingTime(0)
    , posX(0.0)
    , posY(0.0)
    , taskResource()
    , taskUUID()
    , extraMsg()  {
    }
  taskInfo2CoordinatorMessage_(const ContainerAllocator& _alloc)
    : sendingTime(0)
    , infoTypeID(0)
    , receiverRobotID(0)
    , senderRobotID(0)
    , encounteringRobotID(0)
    , encounteringTime(0)
    , handlingDuration(0)
    , timeOutDuration(0)
    , startHandlingTime(0)
    , posX(0.0)
    , posY(0.0)
    , taskResource(_alloc)
    , taskUUID(_alloc)
    , extraMsg(_alloc)  {
  (void)_alloc;
    }



   typedef uint64_t _sendingTime_type;
  _sendingTime_type sendingTime;

   typedef uint16_t _infoTypeID_type;
  _infoTypeID_type infoTypeID;

   typedef uint16_t _receiverRobotID_type;
  _receiverRobotID_type receiverRobotID;

   typedef uint16_t _senderRobotID_type;
  _senderRobotID_type senderRobotID;

   typedef uint16_t _encounteringRobotID_type;
  _encounteringRobotID_type encounteringRobotID;

   typedef uint64_t _encounteringTime_type;
  _encounteringTime_type encounteringTime;

   typedef uint16_t _handlingDuration_type;
  _handlingDuration_type handlingDuration;

   typedef uint16_t _timeOutDuration_type;
  _timeOutDuration_type timeOutDuration;

   typedef uint64_t _startHandlingTime_type;
  _startHandlingTime_type startHandlingTime;

   typedef float _posX_type;
  _posX_type posX;

   typedef float _posY_type;
  _posY_type posY;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _taskResource_type;
  _taskResource_type taskResource;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _taskUUID_type;
  _taskUUID_type taskUUID;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _extraMsg_type;
  _extraMsg_type extraMsg;





  typedef boost::shared_ptr< ::ISLH_msgs::taskInfo2CoordinatorMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ISLH_msgs::taskInfo2CoordinatorMessage_<ContainerAllocator> const> ConstPtr;

}; // struct taskInfo2CoordinatorMessage_

typedef ::ISLH_msgs::taskInfo2CoordinatorMessage_<std::allocator<void> > taskInfo2CoordinatorMessage;

typedef boost::shared_ptr< ::ISLH_msgs::taskInfo2CoordinatorMessage > taskInfo2CoordinatorMessagePtr;
typedef boost::shared_ptr< ::ISLH_msgs::taskInfo2CoordinatorMessage const> taskInfo2CoordinatorMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ISLH_msgs::taskInfo2CoordinatorMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ISLH_msgs::taskInfo2CoordinatorMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ISLH_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ISLH_msgs': ['/home/berkay/catkin_ws/src/ISLH_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ISLH_msgs::taskInfo2CoordinatorMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ISLH_msgs::taskInfo2CoordinatorMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ISLH_msgs::taskInfo2CoordinatorMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ISLH_msgs::taskInfo2CoordinatorMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ISLH_msgs::taskInfo2CoordinatorMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ISLH_msgs::taskInfo2CoordinatorMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ISLH_msgs::taskInfo2CoordinatorMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0297b8535571357f947ead3aedb14c47";
  }

  static const char* value(const ::ISLH_msgs::taskInfo2CoordinatorMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0297b8535571357fULL;
  static const uint64_t static_value2 = 0x947ead3aedb14c47ULL;
};

template<class ContainerAllocator>
struct DataType< ::ISLH_msgs::taskInfo2CoordinatorMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ISLH_msgs/taskInfo2CoordinatorMessage";
  }

  static const char* value(const ::ISLH_msgs::taskInfo2CoordinatorMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ISLH_msgs::taskInfo2CoordinatorMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# The task's information to coalition leader\n\
\n\
uint64 sendingTime #The sending time\n\
\n\
uint16 infoTypeID\n\
\n\
uint16 receiverRobotID #robot id to which the message will be sent \n\
\n\
uint16 senderRobotID #robot id of coalition leader\n\
\n\
uint16 encounteringRobotID #robot id which encounters the task\n\
\n\
uint64 encounteringTime #The encountering time\n\
\n\
uint16 handlingDuration\n\
\n\
uint16 timeOutDuration\n\
\n\
uint64 startHandlingTime #the time when the task starts being handled\n\
\n\
float32 posX # The position of the task at x direction\n\
float32 posY # The position of the task at y direction\n\
\n\
string taskResource\n\
\n\
string taskUUID # the task's UUID\n\
\n\
string extraMsg\n\
\n\
";
  }

  static const char* value(const ::ISLH_msgs::taskInfo2CoordinatorMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ISLH_msgs::taskInfo2CoordinatorMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sendingTime);
      stream.next(m.infoTypeID);
      stream.next(m.receiverRobotID);
      stream.next(m.senderRobotID);
      stream.next(m.encounteringRobotID);
      stream.next(m.encounteringTime);
      stream.next(m.handlingDuration);
      stream.next(m.timeOutDuration);
      stream.next(m.startHandlingTime);
      stream.next(m.posX);
      stream.next(m.posY);
      stream.next(m.taskResource);
      stream.next(m.taskUUID);
      stream.next(m.extraMsg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct taskInfo2CoordinatorMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ISLH_msgs::taskInfo2CoordinatorMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ISLH_msgs::taskInfo2CoordinatorMessage_<ContainerAllocator>& v)
  {
    s << indent << "sendingTime: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.sendingTime);
    s << indent << "infoTypeID: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.infoTypeID);
    s << indent << "receiverRobotID: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.receiverRobotID);
    s << indent << "senderRobotID: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.senderRobotID);
    s << indent << "encounteringRobotID: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.encounteringRobotID);
    s << indent << "encounteringTime: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.encounteringTime);
    s << indent << "handlingDuration: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.handlingDuration);
    s << indent << "timeOutDuration: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.timeOutDuration);
    s << indent << "startHandlingTime: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.startHandlingTime);
    s << indent << "posX: ";
    Printer<float>::stream(s, indent + "  ", v.posX);
    s << indent << "posY: ";
    Printer<float>::stream(s, indent + "  ", v.posY);
    s << indent << "taskResource: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.taskResource);
    s << indent << "taskUUID: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.taskUUID);
    s << indent << "extraMsg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.extraMsg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ISLH_MSGS_MESSAGE_TASKINFO2COORDINATORMESSAGE_H
